//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ql_ThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOPY
    {
        public int MaGY { get; set; }
        public string TieuDe { get; set; }
        public System.DateTime NgayGui { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaND { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
