//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ql_ThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.GOPY = new HashSet<GOPY>();
        }
    
        public int MaNguoiDung { get; set; }
        public string TenNguoiDung { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public Nullable<int> MaQTC { get; set; }
        public Nullable<int> MaTheMuon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOPY> GOPY { get; set; }
        public virtual THEMUON THEMUON { get; set; }
        public virtual QUYENTRUYCAP QUYENTRUYCAP { get; set; }
    }
}
