//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ql_ThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEMUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THEMUON()
        {
            this.MUONXE = new HashSet<MUONXE>();
            this.NGUOIDUNG = new HashSet<NGUOIDUNG>();
        }
    
        public int MaTheMuon { get; set; }
        public string TaiKhoanNganHang { get; set; }
        public Nullable<int> SoDu { get; set; }
        public string TenNganHang { get; set; }
        public Nullable<int> MaLoaiTheMuon { get; set; }
        public string PassTheMuon { get; set; }
    
        public virtual LOAITHEMUON LOAITHEMUON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUONXE> MUONXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOIDUNG> NGUOIDUNG { get; set; }
    }
}
