//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Ql_ThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.MUONXE = new HashSet<MUONXE>();
        }
    
        public int MaXe { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaTram { get; set; }
    
        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUONXE> MUONXE { get; set; }
        public virtual TRAM TRAM { get; set; }
    }
}
